[package]
name = "corelib"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.fs.rs"

[dependencies]
fable_library_rust = { path = "./src/fable_modules/fable-library-rust", features = [], default-features = false }